include:
  - ./docker-compose-base.yml

services:
  ragflow:
    depends_on:
      mysql:
        condition: service_healthy
    image: ${RAGFLOW_IMAGE}
    container_name: ragflow-server
    volumes:
      - ./ragflow-logs:/ragflow/logs
      - ./nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    env_file: .env
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - MACOS=${MACOS}
    networks:
      - ragflow
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ragflow.rule=Host(`kb.laminatedshim.local`) && PathPrefix(`/ragflow`)"
      - "traefik.http.routers.ragflow.entrypoints=web"
      - "traefik.http.middlewares.ragflow-strip.stripprefix.prefixes=/ragflow"
      - "traefik.http.routers.ragflow.middlewares=ragflow-strip@docker"
      - "traefik.http.services.ragflow.loadbalancer.server.port=${SVR_HTTP_PORT}"
      # HTTPS
      - "traefik.http.routers.ragflow-secure.rule=Host(`kb.laminatedshim.local`) && PathPrefix(`/ragflow`)"
      - "traefik.http.routers.ragflow-secure.entrypoints=websecure"
      - "traefik.http.routers.ragflow-secure.tls=true"
      - "traefik.http.routers.ragflow-secure.middlewares=ragflow-strip@docker"
    restart: on-failure
    # https://docs.docker.com/engine/daemon/prometheus/#create-a-prometheus-configuration
    # If you're using Docker Desktop, the --add-host flag is optional. This flag makes sure that the host's internal IP gets exposed to the Prometheus container.
    extra_hosts:
      - "host.docker.internal:host-gateway"
  # executor:
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #   image: ${RAGFLOW_IMAGE}
  #   container_name: ragflow-executor
  #   volumes:
  #     - ./ragflow-logs:/ragflow/logs
  #     - ./nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf
  #   env_file: .env
  #   environment:
  #     - TZ=${TIMEZONE}
  #     - HF_ENDPOINT=${HF_ENDPOINT}
  #     - MACOS=${MACOS}
  #   entrypoint: "/ragflow/entrypoint_task_executor.sh 1 3"
  #   networks:
  #     - ragflow
  #   restart: on-failure
  #   # https://docs.docker.com/engine/daemon/prometheus/#create-a-prometheus-configuration
  #   # If you're using Docker Desktop, the --add-host flag is optional. This flag makes sure that the host's internal IP gets exposed to the Prometheus container.
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"


networks:
  traefik-network:
    external: true